### ISSUE TITLE
change all for-loops in unit tests to parametrised tests

### ISSUE THREAD

**Issue by lukashergt** [handley-lab/anesthetic#110]
Instead of using for-loops in unit tests it would be better to use parametrised tests using [@pytest.mark.parametrize](https://docs.pytest.org/en/stable/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions). These decorators can also be stacked on top of each other in which case all combinations are performed (the equivalent of nested for-loops). 

Using parametrised tests has the huge advantage that a failed test will tell which parametrisation exactly caused the issue, which would be lost in a for-loop.

Some of the unit tests have already been converted to parametrised tests. It would be good to extend that to all other tests that involve for-loops.

**Comment by williamjameshandley** [comment]
Partially implemented by @lukashergt in #109 and #99.

**Comment by williamjameshandley** [comment]
We should also move to more skips of e.g. fgivenx and astropy rather than checks #314
