### ISSUE TITLE
Transfer ownership to handley-lab

### ISSUE THREAD

**Issue by williamjameshandley** [handley-lab/anesthetic#225]
At the moment anesthetic is hosted on my personal github. It would be more professional to transfer it to an organisation. I have an unpopulated organisation [handley-lab](https://github.com/orgs/handley-lab) which I plan to migrate repositories such as [fgivenx](https://github.com/williamjameshandley/fgivenx) to, and this would be a natural place to put anesthetic. 

GitHub is clever enough that when moving a repository it creates a redirect link, and pushing, pulling and cloning still works to the original link, i.e. `git clone git@github.com:williamjameshandley/anesthetic` would still work.

Does anybody object to this move as part of anesthetic 2.0, or see problems with it?

**Comment by lukashergt** [comment]
If cloning and pip installing still works, then no objection from my side.

**Comment by Ormorod** [comment]
thinking we might want to do this before the anesthetic 2 paper is released? just in case any links get broken

**Comment by Ormorod** [comment]
#271 has broken my tests locally; might want to quickly fix this first
