### ISSUE TITLE
Pandas 2 `inplace` deprecation

### ISSUE THREAD

**Issue by AdamOrmondroyd** [handley-lab/anesthetic#233]
The Pandas team intend to depreciate the inplace parameter ready for Pandas 2, see the issue [16529](https://github.com/pandas-dev/pandas/issues/16529).

With respect to anesthetic, [Pandas 1.5.0](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html) deprecated `inplace` from `DataFrame.set_axis()` and replaced it with `copy`:

```
df.set_axis(..., inplace=True)
```
should be replaced with
```
df = df.set_axis(..., copy=False)
```
There are others (e.g. `Series.set_axis()` and several methods of `Categorical`), and I would expect more to follow.

`DataFrame.iteritems()` has also been deprecated in favour of `DataFrame.items()`

**Comment by Ormorod** [comment]
- [ ] I've successfully merged my changes to how pandas `HistPlot` handles weights, which I have copied into #235. This is a reminder to remove this once we move to pandas 2.

**Comment by Ormorod** [comment]
Looks like [about two weeks](https://github.com/pandas-dev/pandas/releases/tag/v2.0.0rc0) until Pandas 2 is here...

**Comment by williamjameshandley** [comment]
Resolved by #292

**Comment by lukashergt** [comment]
Can this issue be closed?

**Comment by AdamOrmondroyd** [comment]
I suppose so, the "more to follow" never arrived…
