### ISSUE TITLE
Returning non-None value in test functions

### ISSUE THREAD

**Issue by AdamOrmondroyd** [handley-lab/anesthetic#242]
Since `pytest` 7.2, a [`pytest.PytestReturnNotNoneWarning`](https://docs.pytest.org/en/latest/deprecations.html#returning-non-none-value-in-test-functions) is emitted if a test function returns something other than `None`. However, `test_labelled_pandas.py` makes extensive use of returning the tested Series/DataFrame, so that they can be used in other tests.

I've started dealing with this in #234, but I thought it appropriate to make an issue to highlight this change.

**Comment by Ormorod** [comment]
I'll have a have a go at changing this around. I might try moving some things around, at a glance I think the contents of `test_constructors()` should just be in the fixtures?

Should this be a separate PR? Struggling to bring myself to look at all the warnings again I dealt with in #234

**Comment by AdamOrmondroyd** [comment]
Fixed in #234
