### ISSUE TITLE
Retain latex label when slicing DataFrame to Series

### ISSUE THREAD

**Issue by AdamOrmondroyd** [handley-lab/anesthetic#253]
When a dataframe of nested samples is sliced to a smaller dataframe, it retains the latex labels, e.g:

```
>>> ns[['x0']]
                          x0
labels                 $x_0$
     weights
0    0.000000e+00   0.839566
1    1.088407e-308  0.711607
2    4.830017e-301 -0.703718
3    6.951167e-262  0.980678
4    7.661544e-241  0.727711
...                      ...
>>> ns[['x0']].get_labels()
array(['$x_0$'], dtype=object)
```

However, if it is sliced to a series, the latex labels are lost:
```
>>> ns['x0']
      weights
0     0.000000e+00     0.839566
1     1.088407e-308    0.711607
2     4.830017e-301   -0.703718
3     6.951167e-262    0.980678
4     7.661544e-241    0.727711
                         ...
>>> ns['x0'].get_labels()
array([0.00000000e+000, 1.08840734e-308, 4.83001654e-301, ...,
       2.31405635e-001, 2.33317335e-001, 2.38103982e-001])
```

This is unfortunate, as all the plotting uses the series rather than dataframes, and it would be nice if the axes and legends could use the latex labels where they exist.

```
>>> ns.plot.kde_2d('x0', 'x1')
```
<img width="638" alt="Screenshot 2023-01-19 at 12 32 41" src="https://user-images.githubusercontent.com/52655393/213443921-46226235-5f09-4f4b-979b-b84329527cf9.png">

**Comment by Ormorod** [comment]
If `NestedSamples` are cast to `DataFrame`, then `labels` are retained after slicing, and shown in e.g.
```
ns['x0'].plot.kde()
df = pd.DataFrame(ns)
df['x0'].plot.kde()
plt.show()
```
`NestedSamples`
<img width="563" alt="Screenshot 2023-02-10 at 16 42 04" src="https://user-images.githubusercontent.com/52655393/218147174-97de4fb2-450a-43db-ade8-82cb8b3c6676.png">

`DataFrame`
<img width="564" alt="Screenshot 2023-02-10 at 16 42 52" src="https://user-images.githubusercontent.com/52655393/218147366-81ae4115-15a2-4b45-acb7-c9e6ba2e7b65.png">
