### ISSUE TITLE
Inconsistent colours on 2D KDE

### ISSUE THREAD

**Issue by yallup** [handley-lab/anesthetic#286]
This may be a feature, or sensible behaviour I am misinterpreting so apologies if this is wrongly raised as a bug report, running with anesthetic 2.0.0b28

**Describe the bug**
When creating a 2D KDE, in particular with the cmap and levels arguments (this is a really nice feature imo for really visually pleasing contours), the colors of the level sets are not consistent across all subplots

**To Reproduce**
Following from the snippets in the quick start (https://anesthetic.readthedocs.io/en/latest/plotting.html#colour):

```python
a = post.plot_2d(a,kinds=dict(diagonal='kde_1d', lower='kde_2d'),label="Posterior" , lower_kwargs=dict(cmap=plt.cm.magma_r,levels=[0.997, 0.954, 0.683]))
```
I produce something like:

![corner_mu](https://user-images.githubusercontent.com/6486664/235188516-04196ddc-4297-4774-adc6-a5bcce62ffb6.png)

**Expected behavior**
I expect my three level sets to be consistently coloured between the 2d marginals but they seem to be shaded differently. I interpret the levels argument as asking for the 1,2,3 sigma intervals on the gaussian kde so should be identically coloured for all.

I note that I think this happens still if I remove all lower_kwargs, it's just in monochrome plots it's harder to notice.

![corner_mu](https://user-images.githubusercontent.com/6486664/235189745-c7615641-6fb0-4e3b-b1cd-57025ed4b5d0.png)

**Comment by lukashergt** [comment]
Hi @yallup,

this is indeed a feature. The levels are defined by the probability mass that they contain. The colours are defined by the probability density within those levels. This is particularly useful for (uninformative) prior distributions (see also the [last paragraph of our docs on prior distributions](https://anesthetic.readthedocs.io/en/latest/samples.html#prior-distribution), where the similar colours per level reflect the uniformity of the distribution: 

![image](https://user-images.githubusercontent.com/18258042/235211367-2f018697-a332-4237-a983-6370070b0faf.png)

In the above plot the `x0`-`x1` prior contours would look very non-uniform if the colour gradient would be as steep as for the posterior contours.
