### ISSUE TITLE
Incorrect link in samples.rst

### ISSUE THREAD

**Issue by htjb** [handley-lab/anesthetic#300]
I think that the line

```
Gaussian model dimensionality :meth:`anesthetic.samples.NestedSamples.logL_P`:raw-html:`<br />`
```
in `samples.rst` in the section on `Bayesian statistics` should be

```
Gaussian model dimensionality :meth:`anesthetic.samples.NestedSamples.d_G`:raw-html:`<br />`
```

as it's currently linking to docs for the posterior average of the likelihood not the model dimensionality.

**Comment by lukashergt** [comment]
Indeed, thanks @htjb, even if it is just a very small change, issues like this help tremendously in creating good docs.

Addressed in #301.
