### ISSUE TITLE
Plots with logL birth

### ISSUE THREAD

**Issue by mj-will** [handley-lab/anesthetic#310]
As discussed with @lukashergt, whilst passing samples from [nessai](https://github.com/mj-will/nessai) and producing plots, I ran into something that I found slightly confusing. 

Here's some pseudocode for what I was doing:

```python
nested_samples =   ... # np.ndarray
names = ... # List[str]
logL = ... # np.ndarray
logL_birth = ... # np.ndarray (contains -inf)

samples = NestedSamples(
    nested_samples,
    columns=names,
    logL=logL,
    logL_birth=logL_birth,
)
samples.plot_1d()
```

This produces a `ValueError` because of the -infs in `logL_birth`. 

I found this counterintuitive because I assumed calling `samples.plot_1d()` would work if I had passed the correct inputs to `NestedSamples`. Given `logL_birth` will typically contain -inf (or very negative numbers), do you think there should be a special case for this column so that it doesn't fail?

**Comment by lukashergt** [comment]
First off, thanks @mj-will for raising this.

@williamjameshandley, if I remember correctly you already started on something regarding this, right?
